### ISSUE TITLE
Install broken because of node

### ISSUE THREAD

**Issue by mikkeschiren** [nodeone/impono#9]
Following the readme, now it is not possible to install the project on "fresh" computer:

`gulp build`

```
[11:03:27] Failed to load external module ts-node/register
[11:03:27] Failed to load external module typescript-node/register
[11:03:27] Failed to load external module typescript-register
[11:03:27] Failed to load external module typescript-require
/srv/www/impono/Gulpfile.ts:143
function fonts(sassSource: string, cssDest: string) {
                         ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/home/myuser/.nvm/versions/node/v6.2.2/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/myuser/.nvm/versions/node/v6.2.2/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
```

**Comment by mikkeschiren** [comment]
This should solve the problem nodeone/impono/pull/10
